/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_kt_glsample_JniUtils */

#ifndef _Included_com_example_kt_glsample_JniUtils
#define _Included_com_example_kt_glsample_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_kt_glsample_JniUtils
 * Method:    glReadPixels
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_example_kt_glsample_JniUtils_glReadPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
