#include "stdafx.h"
#include "Solution.h"

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

char Solution::findTheDifference(string s, string t)
{
    for (int j = 0; j < t.size(); j++)
    {
        bool find = false;
        for (int i = 0; i < s.size(); i++)
        {
            if (s[i] == t[j])
            {
                find = true;
                s[i] = ' ';
                break;
            }
        }

        if (find == false)
        {
            return t[j];
        }
    }

    return ' ';
}